kind: pipeline
type: exec
name: Judge-Girl/Judge-Girl

steps:
  - name: Info
    commands:
      - "export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.9.11-2.el7_9.x86_64"
      - "echo $(whoami)"
      - "echo Workspace: $(pwd)"
      - "echo Maven: $(mvn -v)"
      - "echo JAVA_HOME: $JAVA_HOME"
      - printenv
  - name: Prepare
    commands:
      - git submodule update --recursive --init
      - export workspace=$(pwd)
      - cd /root/drone/judgegirl/judge-girl-secrets/
      - echo `pwd`
      - cp -r ./* $workspace
      - cd $workspace
  - name: Integration
    commands:
      - export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.9.11-2.el7_9.x86_64
      - mvn package --quiet
  - name: Build Docker Image
    commands:
      - cd Judger/ && docker build . -t judger -f Dockerfile.cqi && cd ..
      - docker-compose -f services.yml build
    when:
      branch:
        - master
        - dev/147
      event:
        - push
  - name: Deploy
    commands:
      - docker network create judge-girl || echo "Network 'judge-girl' already exists"
      - docker-compose -f infra.yml up -d
      - docker-compose -f services.yml down
      - docker-compose -f services.yml up -d
    when:
      branch:
        - master
        - dev/147
      event:
        - push