kind: pipeline
type: exec
name: Judge-Girl/Judge-Girl

steps:
  - name: Info
    commands:
      - "echo $(whoami)"
      - "echo Workspace: $(pwd)"
      - "echo Maven: $(mvn -v)"
      - "echo JAVA_HOME: $JAVA_HOME"
      - printenv
  - name: Prepare
    commands:
      - git submodule update --recursive --init
      - export workspace=$(pwd)
      - cd /root/drone/judgegirl/judge-girl-secrets/
      - echo `pwd`
      - cp -r ./* $workspace
      - cd $workspace
  - name: Integration
    commands:
      - ./mvnw package --quiet
  - name: Build Docker Image
    commands:
      - cd Judger/ && docker build . -t judger -f Dockerfile.cqi && cd ..
      - docker-compose -f services.yml build
    when:
      branch:
        - master
      event:
        - push
  - name: Deploy
    commands:
      - docker network create judge-girl || echo "Network 'judge-girl' already exists"
      - docker-compose -f infra.yml up -d
      - sleep 10
      - docker-compose -f services.yml down
      - docker-compose -f services.yml up -d
    when:
      branch:
        - master
      event:
        - push