version: '2.0'
services:
  student-service:
    build: Student-Adapter-Service
    environment:
      spring.profiles.active: prod
    networks:
      - host
      - judge-k8s

  problem-service:
    build: Problem-Service
    environment:
      spring.profiles.active: dev
    networks:
      - judge-k8s


  submission-service:
    build: Submission-Service
    environment:
      spring.profiles.active: dev,serviceDriver,jwt
    networks:
      - judge-k8s

  web-gateway:
    build: app
    ports:
      - 80:80
    networks:
      - judge-k8s

networks:
  judge-k8s:
