version: '3.0'

networks:
  default:
    external:
      name: judge-girl

services:
  reverse-proxy:
    image: traefik:v2.3
    command:
      - "--entryPoints.web.address=:80"
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  student-service:
    build: Spring-Boot/Spring-Boot-Student
    environment:
      spring.profiles.active: prod,mysql,amqp
      MYSQL_HOST: "${MYSQL_HOST}"
      RABBIT_HOST: "${RABBIT_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.student-service.rule=PathPrefix(`/broker`) || PathPrefix(`/api/students`) || PathPrefix(`/api/admins`)"
      - "traefik.http.routers.student-service.entrypoints=web"
      - "traefik.http.routers.student-service.service=student-service"
      - "traefik.http.services.student-service.loadbalancer.server.port=80"
      - "traefik.http.routers.student-service.priority=1"

  academy-service:
    build: Spring-Boot/Spring-Boot-Academy
    environment:
      spring.profiles.active: prod,amqp,mysql
      MYSQL_HOST: "${MYSQL_HOST}"
      RABBIT_HOST: "${RABBIT_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.academy-service.rule=PathPrefix(`/api/exams`) || PathPrefix(`/api/students/{studentId:[0-9]+}/exams`) || PathPrefix(`/api/homework`) || PathPrefix(`/api/members`) || PathPrefix(`/api/groups`)"
      - "traefik.http.routers.academy-service.entrypoints=web"
      - "traefik.http.routers.academy-service.service=academy-service"
      - "traefik.http.services.academy-service.loadbalancer.server.port=80"
      - "traefik.http.routers.academy-service.priority=3"

  problem-service:
    build: Spring-Boot/Spring-Boot-Problem
    environment:
      spring.profiles.active: prod,mongo
      MONGO_HOST: "${MONGO_HOST}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.problem-service.rule=PathPrefix(`/api/problems`) || PathPrefix(`/api/plugins`)"
      - "traefik.http.routers.problem-service.entrypoints=web"
      - "traefik.http.routers.problem-service.service=problem-service"
      - "traefik.http.services.problem-service.loadbalancer.server.port=80"
      - "traefik.http.routers.problem-service.priority=2"

  submission-service:
    build: Spring-Boot/Spring-Boot-Submission
    environment:
      spring.profiles.active: prod,mongo,amqp
      MONGO_HOST: "${MONGO_HOST}"
      RABBIT_HOST: "${RABBIT_HOST}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # docker-in-docker for running judger
    command: "/bin/sh -c 'until nc -z -v -w30 ${RABBIT_HOST} 5672; do echo Waiting for RabbitMQ...; sleep 1; done && java -jar /app.jar'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.submission-service.rule=PathPrefix(`/api/submissions`) || PathPrefix(`/api/problems/{problemId:[0-9]+}/{langEnv:\\w+}/students/{studentId:[0-9]+}/submissions`) || PathPrefix(`/api/problems/{problemId:[0-9]+}/samples`)"
      - "traefik.http.routers.submission-service.entrypoints=web"
      - "traefik.http.routers.submission-service.service=submission-service"
      - "traefik.http.services.submission-service.loadbalancer.server.port=80"
      - "traefik.http.routers.submission-service.priority=4"

