pipeline {
    agent any
    stages {
        stage('Install Libs') {
            steps {
                build job: "/Judge-K8S.commons", wait: true
                build job: "/Judge-K8S.plugins", wait: true
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Unit Test') {
            steps {
                sh 'mvn -B test'
            }
        }

        stage('Integration Test') {
            steps {
                sh 'mvn -B -DskipTests verify'
            }
        }

        stage('Build image') {
            steps {
                sh 'docker build -t judge-k8s.problem-service:1.0 .'
            }
        }

        stage('Run Image') {
            steps {
                sh 'docker stop judge-k8s.problem-service || true'
                sh 'docker run --network host -d --rm --name judge-k8s.problem-service judge-k8s.problem-service:1.0'
            }
        }
        
    }
}
