spring:
  main:
    lazy-initialization: false
  rabbitmq:
    virtual-host: ${judge-girl.amqp.virtual-host}
    username: ${judge-girl.amqp.username}
    password: ${judge-girl.amqp.password}
    host: ${judge-girl.amqp.host}
    port: ${judge-girl.amqp.port}

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: info

judge-girl:
  amqp:
    virtual-host: /judge-girl
    username: PLACEHOLDER
    password: PLACEHOLDER
    host: ${RABBIT_HOST:localhost}
    port: 5672
    academy-service-queue: Academy-Service
    submission-service-queue: Submission-Service
    broker-queue-format: Broker-%s-%s  # Broker-<event>-<UUID>
    submissions-exchange-name: Submissions
    verdict-issued-routing-key-format: submissions.%s.verdict
    live-submissions-routing-key: submissions
  submission-service:
    save-strategy: copy-on-write # (verdict-shortcut | copy-on-write)
  client:
    problem-service:
      scheme: http
      host: problem-service
      port: 80
    student-service:
      scheme: http
      host: student-service
      port: 80
    submission-service:
      scheme: http
      host: submission-service
      port: 80
  judger:
    # (docker | kubernetes)
    strategy: docker
    job:
      name-format: judge-girl-judger-%s
    image:
      name: johnny850807/judger:3.0.1
    container:
      name-format: judge-girl-judger-%s
    docker:
      # corresponding to the network defined in docker-compose.yml
      network: judge-girl
      # By enabling the log-volume, the Judger container will place its log files in a mounted volume,
      # so that you can bring the log files back from the container to the host.
      # Therefore, you need to specify 'log-volume-host' -- the volume's directory path on the host.
      log-volume-enable: false
      log-volume-host: PLACEHOLDER  # only if you enable the log-volume
      # The interval time of Judge Girl cleaning up the Judger containers that already exited.
      dockerRemovalIntervalInMs: 10000
    kubernetes:
      # the secret can be created following the instructions: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
      # you can replace it according to your secret's name
      image-pull-secret: regcred
      namespace: judgegirl

    amqp:
      host: ${judge-girl.amqp.host}
      port: ${judge-girl.amqp.port}

    # the client configuration that Judger relies on.
    client:
      problem-service:
        scheme: http
        host: problem-service
        port: 80
      student-service:
        scheme: http
        host: student-service
        port: 80
      submission-service:
        scheme: http
        host: submission-service
        port: 80

jwt:
  secret: PLACEHOLDER  # replace with your own jwt secret (at least 30 characters)
  exp: 14400000